## Questão 1- Testes

In [1]:


import numpy as np
from sklearn.neighbors import KNeighborsClassifier
from sklearn.neighbors import KNeighborsRegressor
from sklearn.model_selection import StratifiedKFold
from mylibs import dist_metrics
from mylibs import knn
import pandas as pd

In [2]:
x = knn.KNNClassifier()
X = np.array([[ 2.7810836 ,  2.550537  ],
       [ 1.46548937,  2.36212508],  
       [ 3.39656169,  4.40029353],  
       [ 1.38807019,  1.85022032],  
       [ 3.06407232,  3.00530597],  
       [ 7.62753121,  2.75926224],
       [ 5.33244125,  2.08862677],
       [ 6.92259672,  1.77106367],
       [ 8.67541865, -0.24206865],
       [ 7.67375647,  3.50856301]])
y = np.array([ 0,  0,  0,  0,  0,  1,  1,  1,  1,  1])
X_test =   np.array([[3.06407232,  3.00530597],[ 1.46548937,  2.36212508],[ 6.92259672,  1.77106367]])


Sucess


In [3]:
x.fit(X,y)
x.predict(X_test)

[1, 1, 1]

In [4]:
X1 = knn.KNNRegressor()
X1.fit(X,y)
X1.predict(X_test)

Sucess


[0.8, 0.8, 0.8]

## Questão 2

In [5]:
data = pd.read_csv("winequality-white.csv", header=None)


In [6]:
data.iloc[:,11] = data.iloc[:,11].astype(int)
data.head(9)

0     1     2     3      4     5      6       7     8     9     10  11
0  7.0  0.27  0.36  20.7  0.045  45.0  170.0  1.0010  3.00  0.45   8.8   6
1  6.3  0.30  0.34   1.6  0.049  14.0  132.0  0.9940  3.30  0.49   9.5   6
2  8.1  0.28  0.40   6.9  0.050  30.0   97.0  0.9951  3.26  0.44  10.1   6
3  7.2  0.23  0.32   8.5  0.058  47.0  186.0  0.9956  3.19  0.40   9.9   6
4  7.2  0.23  0.32   8.5  0.058  47.0  186.0  0.9956  3.19  0.40   9.9   6
5  8.1  0.28  0.40   6.9  0.050  30.0   97.0  0.9951  3.26  0.44  10.1   6
6  6.2  0.32  0.16   7.0  0.045  30.0  136.0  0.9949  3.18  0.47   9.6   6
7  7.0  0.27  0.36  20.7  0.045  45.0  170.0  1.0010  3.00  0.45   8.8   6
8  6.3  0.30  0.34   1.6  0.049  14.0  132.0  0.9940  3.30  0.49   9.5   6

Separando Splits

In [7]:
splits = 3
tx = range(data.shape[0])
ty = data.iloc[:,11]
train_index_1 = []
test_index_1 = []
kfold = StratifiedKFold(n_splits=splits, shuffle=True, random_state=42)
for train_index, test_index in kfold.split(tx,ty):
    print(train_index, test_index)
    train_index_1.append(train_index)
    test_index_1.append(test_index)

[   0    1    3 ... 4895 4896 4897] [   2   21   22 ... 4886 4889 4893]
[   1    2    4 ... 4892 4893 4897] [   0    3    5 ... 4894 4895 4896]
[   0    2    3 ... 4894 4895 4896] [   1    4    8 ... 4888 4892 4897]


In [8]:
testX = []
testy = []
trainX = []
trainy = []
for i in range(splits):
    testX.append(np.array(data.iloc[test_index_1[i],0:11]))
    testy.append(np.array(data.iloc[test_index_1[i],11]))
    trainX.append(np.array(data.iloc[train_index_1[i],:11]))
    trainy.append(np.array(data.iloc[train_index_1[i],11]))

In [10]:
skl = KNeighborsClassifier(n_neighbors=3)
myModel1 = knn.KNNClassifier(k=3,metric='euclidean')
myModel2 = knn.KNNClassifier(k=3,metric='manhattan')
y_predsk = []
y_predM1 = []
y_predM2 = []
for i in range(splits):
    skl.fit(trainX[i],trainy[i])
    y_predsk.append(skl.predict(testX[i]))
    
    myModel1.fit(trainX[i],trainy[i])
    y_predM1.append(myModel1.predict(testX[i]))
    
    myModel2.fit(trainX[i],trainy[i])
    y_predM2.append(myModel2.predict(testX[i]))

Sucess
Sucess


In [14]:
splits = 3
for i in range(splits):
    print("Split{}".format(i))
    print(np.unique(y_predsk[i],return_counts=True))
    print(np.unique(y_predM1[i],return_counts=True))
    print(np.unique(y_predM2[i],return_counts=True))

Split0
(array([3, 4, 5, 6, 7, 8]), array([  8,  86, 565, 724, 230,  23]))
(array([5]), array([1636]))
(array([5]), array([1636]))
Split1
(array([3, 4, 5, 6, 7, 8]), array([  8,  67, 544, 741, 243,  30]))
(array([6]), array([1633]))
(array([6]), array([1633]))
Split2
(array([3, 4, 5, 6, 7, 8]), array([ 10,  60, 518, 761, 254,  26]))
(array([6]), array([1629]))
(array([6]), array([1629]))


## Questão 3

Separando Splits

In [11]:
splits = 5
tx = range(data.shape[0])
ty = data.iloc[:,11]
train_index_1 = []
test_index_1 = []
kfold = StratifiedKFold(n_splits=splits, shuffle=True, random_state=42)
for train_index, test_index in kfold.split(tx,ty):
    print(train_index, test_index)
    train_index_1.append(train_index)
    test_index_1.append(test_index)

[   0    1    2 ... 4895 4896 4897] [  25   41   51   53   67   83   84   89   90   92   96  103  104  109
  110  123  130  132  136  140  142  144  146  149  151  153  154  163
  168  173  174  177  185  191  194  198  206  207  210  214  216  228
  233  234  243  246  247  248  251  253  257  259  260  264  270  273
  277  280  293  295  298  301  305  306  316  319  320  324  330  333
  351  375  381  387  390  393  398  408  410  418  419  420  423  424
  430  432  433  440  442  443  452  455  463  473  476  478  487  488
  489  491  496  497  498  500  501  514  517  518  520  523  526  529
  532  533  540  541  545  548  551  553  559  566  579  580  582  584
  598  603  612  614  622  624  625  635  638  642  654  661  662  665
  667  668  672  674  682  688  691  694  699  705  707  712  713  714
  716  718  720  721  724  729  741  743  748  751  765  793  796  801
  803  806  809  811  814  820  821  828  831  832  834  844  845  846
  847  849  856  857  860  864  877  878 

In [12]:
testX = []
testy = []
trainX = []
trainy = []
for i in range(splits):
    testX.append(np.array(data.iloc[test_index_1[i],0:11]))
    testy.append(np.array(data.iloc[test_index_1[i],11]))
    trainX.append(np.array(data.iloc[train_index_1[i],:11]))
    trainy.append(np.array(data.iloc[train_index_1[i],11]))

In [13]:
sklR = KNeighborsRegressor(n_neighbors=5)
myModel1R = knn.KNNRegressor(k=5,metric='euclidean')
myModel2R = knn.KNNRegressor(k=5,metric='manhattan')
y_predskR = []
y_predM1R = []
y_predM2R = []
for i in range(splits):
    sklR.fit(trainX[i],trainy[i])
    y_predskR.append(sklR.predict(testX[i]))
    
    myModel1R.fit(trainX[i],trainy[i])
    y_predM1R.append(myModel1R.predict(testX[i]))
    
    myModel2R.fit(trainX[i],trainy[i])
    y_predM2R.append(myModel2R.predict(testX[i]))

Sucess
Sucess


In [15]:
splits = 5
for i in range(splits):
    print("Split{}".format(i))
    print(np.unique(y_predskR[i],return_counts=True))
    print(np.unique(y_predM1R[i],return_counts=True))
    print(np.unique(y_predM2R[i],return_counts=True))

Split0
(array([4. , 4.6, 4.8, 5. , 5.2, 5.4, 5.6, 5.8, 6. , 6.2, 6.4, 6.6, 6.8,
       7. , 7.2, 7.4, 7.6, 7.8, 8. ]), array([  1,   6,  10,  40,  94, 112, 131, 130, 120, 141,  79,  47,  32,
        25,   6,   3,   1,   1,   2]))
(array([5.8]), array([981]))
(array([5.8]), array([981]))
Split1
(array([4.2, 4.4, 4.6, 4.8, 5. , 5.2, 5.4, 5.6, 5.8, 6. , 6.2, 6.4, 6.6,
       6.8, 7. , 7.2, 7.4, 7.6, 8. ]), array([  3,   6,   8,  16,  32,  78,  87, 132, 116, 133, 125,  91,  76,
        36,  28,   5,   5,   2,   2]))
(array([5.8]), array([981]))
(array([5.8]), array([981]))
Split2
(array([4.4, 4.6, 4.8, 5. , 5.2, 5.4, 5.6, 5.8, 6. , 6.2, 6.4, 6.6, 6.8,
       7. , 7.2, 7.4, 8. ]), array([  3,   4,  10,  40,  77,  99, 141, 148, 135,  96,  86,  63,  39,
        24,   8,   4,   3]))
(array([5.8]), array([980]))
(array([5.8]), array([980]))
Split3
(array([4. , 4.2, 4.4, 4.6, 4.8, 5. , 5.2, 5.4, 5.6, 5.8, 6. , 6.2, 6.4,
       6.6, 6.8, 7. , 7.2, 7.4, 8. ]), array([  1,   1,   1,  10,  11,  29, 